tests:
  agent:
    registry:
      k: k
    interpreter:
      llm:
        api-key-filepath: ../openai.key
        model-specs:
          api-max-retries: 5
          model-id: "gpt-4o-mini"
      instructions:
        sys-instruction: ../instructions/agent/interpreter/sys.prompt
        user-instruction: ../instructions/agent/interpreter/user.prompt
    director:
      llm:
        api-key-filepath: ../openai.key
        model-specs:
          api-max-retries: 5
          model-id: "gpt-4o-mini"
      instructions:
        sys-instruction: ../instructions/agent/director/sys.prompt
        user-instruction: ../instructions/agent/director/user.prompt
    planner:
      llm:
        api-key-filepath: ../openai.key
        model-specs:
          api-max-retries: 5
          model-id: "gpt-4o-mini"
      instructions-contributions:
        sys-instruction: ../instructions/agent/planner/sys-contributions.prompt
        user-instruction: ../instructions/agent/planner/user-contributions.prompt
      instructions-query:
        sys-instruction: ../instructions/agent/planner/sys-queries.prompt
        user-instruction: ../instructions/agent/planner/user-queries.prompt
    executor:
      llm:
        api-key-filepath: ../openai.key
        model-specs:
          api-max-retries: 5
          model-id: "gpt-4o-mini"
      instructions:
        sys-instruction: ../instructions/agent/executor/sys.prompt
        user-instruction: ../instructions/agent/executor/user.prompt
  interpreter:
    llm:
      api-key-filepath: ../openai.key
      model-specs:
        api-max-retries: 5
        model-id: "gpt-4o-mini"
    instructions:
      sys-instruction: ../instructions/agent/interpreter/sys.prompt
      user-instruction: ../instructions/agent/interpreter/user.prompt
  planner:
    llm:
      api-key-filepath: ../openai.key
      model-specs:
        api-max-retries: 5
        model-id: "gpt-4o-mini"
    instructions:
      sys-instruction: ../instructions/agent/planner/sys.prompt
      user-instruction: ../instructions/agent/planner/user.prompt
  executor:
    llm:
      api-key-filepath: ../openai.key
      model-specs:
        api-max-retries: 5
        model-id: "gpt-4o-mini"
    instructions:
      sys-instruction: ../instructions/agent/executor/sys.prompt
      user-instruction: ../instructions/agent/executor/user.prompt
    tools:
      k: k
    memory:
      k: k
  advisor:
    llm:
      api-key-filepath: ../openai.key
      model-specs:
        api-max-retries: 5
        model-id: "gpt-4o-mini"
    instructions:
      sys-instruction: ../instructions/agent/advisor/sys.prompt
      user-instruction: ../instructions/agent/advisor/user.prompt